name: "example"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    healthcheck:
      test: mysql -utest -ptest -Dtest
      interval: 1s
      retries: 300
