name: "PR Checker"
on:
  pull_request_review:
    types: [ submitted ]
    branch: [ "main" ]

jobs:
  check2:
    runs-on: ubuntu-latest
    steps:
    - name: Check for Resolves / Fixes
      uses: gsactions/commit-message-checker@v2
      with:
        pattern: '^.+\n.*foo.*$'
        error: 'miss foo'
