name: "PR Title Checker"
on:
  workflow_dispatch: {}
  pull_request_target:
    branches: [ main ]
    types:
    - opened
    - edited
    - synchronize
    - labeled
    - unlabeled
    - closed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Show default environment variables
      run: |
        echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
        echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
        echo "The run id is: $GITHUB_RUN_ID"
        echo "The GitHub Actor's username is: $GITHUB_ACTOR"
        echo "GitHub SHA: $GITHUB_SHA"

    - run: env && echo "This PR was approved"
    - name: Check for Resolves / Fixes
      uses: gsactions/commit-message-checker@v2
      with:
        pattern: '^.+\n.*foo.*$'
        error: 'miss foo'
    - uses: thehanimo/pr-title-checker@v1.3.6
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pass_on_octokit_error: false
        configuration_path: ".github/workflows/pr-title-checker-config.json"
